# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Disco < Formula
  desc "Utility for bulk image, license, and vulnerability discovery in containerize workloads on GCP."
  homepage "https://github.com/mchmarny/disco"
  version "1.1.1"
  license "Apache-2.0"

  on_macos do
    url "https://github.com/mchmarny/disco/releases/download/v1.1.1/disco_1.1.1_darwin_all"
    sha256 "26853812ebf52dbf928319e92be45f6f823e84de564170351d84e11c431bf701"

    def install
      bin.install "disco_1.1.1_darwin_all" => "disco"
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/mchmarny/disco/releases/download/v1.1.1/disco_1.1.1_linux_arm64"
      sha256 "3a14ff6ee1b52272a54fab093a439c782d873bbed36bb6eb13693d748eb32afb"

      def install
        bin.install "disco_1.1.1_linux_arm64" => "disco"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/mchmarny/disco/releases/download/v1.1.1/disco_1.1.1_linux_amd64"
      sha256 "4a3df804d8caec01b40cc98141eae8c590584cb57ba61e6384beff1136346f7b"

      def install
        bin.install "disco_1.1.1_linux_amd64" => "disco"
      end
    end
  end

  test do
    system "#{bin}/disco --version"
  end
end
